version:
  name: velociraptor
  version: 0.74.0-rc1
  commit: 445a661
  build_time: "2025-02-25T22:38:58Z"
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/13532308717
  compiler: go1.23.6
  system: linux
  architecture: amd64
Client:
  server_urls:
  - https://34.118.75.59:80/
  ca_certificate: | 
  -----BEGIN CERTIFICATE-----
  MIIDVzCCAj+gAwIBAgIQBwx5Yx8w58NNdwr/TeMCrjANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjUwMjI3MTgxNDM2WhcNMjYw
  MjI3MTgxNDM2WjA0MRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxGzAZBgNVBAMTElZl
  bG9jaXJhcHRvclNlcnZlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
  AKL5MD7dQ45k/gR29aLABltx49esYAHHuB0LK36RutflYU19k8SHQyljOL7hAovj
  7ppdoLB9MjKOSi1UMTv+FU5rZTMn491RC8vHDvf3NzSUG3i5wIQdXnzjhoVcv50x
  m5EF0YLir4sSfXGkuOfEPS8K25AfMvefG/RUHSAJ4pN/whY6rIHUZNZ8cGVaEpYD
  6p/AxxayInA0kByyoa++LY/n0fodp4qzRxIsQqMHzyfr0TERvZGvhVh7vcyHGREH
  7Ly3Bia1jQCTkxvylilh7IIgajL4uMYmcSSE+pfLUxtjhw464Xu38Gph0l1oNCCn
  oWIAVWRXCO/k0YtCua2ydA0CAwEAAaN/MH0wDgYDVR0PAQH/BAQDAgWgMB0GA1Ud
  JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQY
  MBaAFJ7ikgDhDJfEQeNM9GbLBPbXHtC1MB0GA1UdEQQWMBSCElZlbG9jaXJhcHRv
  clNlcnZlcjANBgkqhkiG9w0BAQsFAAOCAQEAvMUeI0Q59DMvJqQjBvU9I2tTGRps
  iii9QC7JtTQir83R+zzKW7YX8PcEw/Q+P7lL7lhDUVjeG6YaBP4f+mirrugyvqEk
  saQHl3cO788zQyH0OO8Qv7CIgD4l4vtJTJ4TaQYhogGZ0rQUOwMguci0WUwW12sn
  6JnXmWIuFDE02zWYWX2gLPtHzs/17b683GITrPBZdJjvVff2W3zIq6bqqKXZBaud
  q1SIV5otIRYX986u23iI6cLxA4gP0Rpb/uSSEQUbgA4EIiR7wDLmObad3wfmxIbl
  tOvmeu3bCZOT5FuoeyifiSh4j320bMoGiEkOJQyTHGl3B+m8iRSJtY6e/Q==
  -----END CERTIFICATE-----
  nonce: 8sqxa2V2m6g=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.74.0-rc1
    commit: 445a661
    build_time: "2025-02-25T22:38:58Z"
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/13532308717
    compiler: go1.23.6
    system: linux
    architecture: amd64
  server_version:
    version: 0.74.0-rc1
    commit: 445a661
    build_time: "2025-02-25T22:38:58Z"
  use_self_signed_ssl: true
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
